image: node:latest

cache:
  paths:
    - node_modules/

pages:
  stage: deploy
  tags:
    - pages
  script:
    - npm install
    - npm run build
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master
