image: node:latest

cache:
  paths:
    - node_modules/


pages:
  stage: deploy
  script:
  - webpack --env.mode production --config ./webpack/config.js
  artifacts:
    paths:
    - public
  only:
  - master

