image: node:latest

cache:
  paths:
    - node_modules/


pages:
  stage: deploy
  script:
  - webpack --env.mode production --config ./webpack/config.js
  artifacts:
    paths:
    - public
  only:
  - master


test_async:
  script:
    - npm install
    - node ./specs/start.js ./specs/async.spec.js

test_db:
  script:
    - npm install
    - node ./specs/start.js ./specs/db-postgres.spec.js
